---
title: "Ames"
author: "David Stroud"
date: "2/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# get the require R packages
library(ggplot2)
library(plyr)
library(dplyr)
library(caret)
library(moments)
library(glmnet)
library(elasticnet)
library(knitr)

options(width=100)
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)


ROOT.DIR <- ".."   #facilitates testing inside and outside of Rmarkdown notebook
```

```{r}
# load the datasets
# note ~ use read.csv to read into Rmd
train <- read.csv("train.csv")
test <- read.csv("test.csv")
```

```{r}
# show the first few rows of training data
head(train)
```

```{r}
# show the dimensions of training data sample
dim(head(train))
```

```{r}
# combine train and test data for preprocessing
all_data <- rbind(select(train,MSSubClass:SaleCondition),
                  select(test,MSSubClass:SaleCondition))
```


```{r}
df <- rbind(data.frame(version="log(price+1)",x=log(train$SalePrice + 1)),
            data.frame(version="price",x=train$SalePrice))

# plot histogram
ggplot(data = df) +
  facet_wrap(~version,ncol = 2,scales = "free_x") +
  geom_histogram(aes(x=x))
```













