---
title: "Playground"
author: "David Stroud"
date: "2/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2) # Data visualization
library(readr) # CSV file I/O, e.g. the read_csv function
library(dplyr)
```

```{r}
# load the datasets
# note ~ use read.csv to read into Rmd
train <- read.csv("train.csv")
test <- read.csv("test.csv")
summary(train)
str(train)
```            

```{r}
# Show the dimensions of the training data sample
dim(head(train))
```

```{r}
# Show scatter plot ~ 
ggplot(train,aes(y=SalePrice,x=GrLivArea))+geom_point()
```

```{r}
# Remove outliers. Data points where GrLivArea is about 4000
train <- train[train$GrLivArea<=4000,]
```
 
 
```{r}
# The majority of garages were built when the homes were built. Points
# above the line show they were added later
# Consider building a new feature that tells us whether or not a garage
# was originally constructed with the house or when it was added.
ggplot(train,aes(y=GarageYrBlt,x=YearBuilt))+geom_point()
```

 
 
 
 
 
 
 
 