---
title: "Ames"
author: "David Stroud"
date: "2/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# get the require R packages
library(ggplot2) # Data visualization
library(readr) # CSV file I/O, e.g. the read_csv function
library(MASS)
library(dplyr)
library(lars)
library(moments)
library(caret)
library(corrplot)
library(gbm)
```

```{r}
# load the datasets
# note ~ use read.csv to read into Rmd
train <- read.csv("train.csv")
test <- read.csv("test.csv")
summary(train)
str(train)
```

```{r}
# show the first few rows of training data
head(train)
```

```{r}
# show the dimensions of training data sample
dim(head(train))
```

```{r}
ggplot(train,aes(y=SalePrice,x=GrLivArea))+geom_point()
```



```{r}
train <- train[train$GrLivArea<=4000,]
```



```{r}
Missing_indices <- sapply(train,function(x)sum(is.na(x)))
Missing_Summary <- data.frame(index = names(train),Missing_Values=Missing_indices)
Missing_Summary[Missing_Summary$Missing_Values > 0,]
```


```{r}
#combining train and test data for quicker data prep
test$SalePrice <- NA
train$isTrain <- 1
test$isTrain <- 0
combined <- rbind(train,test)

combined$MasVnrArea[which(is.na(combined$MasVnrArea))] <- mean(combined$MasVnrArea,na.rm=T)
# Changing NA in Alley to None
combined$Alley1 <- as.character(combined$Alley)
combined$Alley1[which(is.na(combined$Alley))] <- "None"
table(combined$Alley1)
combined$Alley <- as.factor(combined$Alley1)
combined <- subset(combined,select = -Alley1)
# Changing NA in MasVnrType to None
combined$MasVnrType1 <- as.character(combined$MasVnrType)
combined$MasVnrType1[which(is.na(combined$MasVnrType))] <- "None"
combined$MasVnrType <- as.factor(combined$MasVnrType1)
combined <- subset(combined,select = -MasVnrType1)
table(combined$MasVnrType)
# Imputing missing Lot Frontage by the median
combined$LotFrontage[which(is.na(combined$LotFrontage))] <- median(combined$LotFrontage,na.rm = T)


# Changing NA in FireplaceQu to None
combined$FireplaceQu1 <- as.character(combined$FireplaceQu)
combined$FireplaceQu1[which(is.na(combined$FireplaceQu))] <- "None"
combined$FireplaceQu <- as.factor(combined$FireplaceQu1)
combined <- subset(combined,select = -FireplaceQu1)

# Changing NA in PoolQC to None
combined$PoolQC1 <- as.character(combined$PoolQC)
combined$PoolQC1[which(is.na(combined$PoolQC))] <- "None"
combined$PoolQC <- as.factor(combined$PoolQC1)
combined <- subset(combined,select = -PoolQC1)

# Changing NA in Fence to None
combined$Fence1 <- as.character(combined$Fence)
combined$Fence1[which(is.na(combined$Fence))] <- "None"
combined$Fence <- as.factor(combined$Fence1)
combined <- subset(combined,select = -Fence1)

# Changing NA in MiscFeature to None
combined$MiscFeature1 <- as.character(combined$MiscFeature)
combined$MiscFeature1[which(is.na(combined$MiscFeature))] <- "None"
combined$MiscFeature <- as.factor(combined$MiscFeature1)
combined <- subset(combined,select = -MiscFeature1)

# Changing NA in GarageType to None
combined$GarageType1 <- as.character(combined$GarageType)
combined$GarageType1[which(is.na(combined$GarageType))] <- "None"
combined$GarageType <- as.factor(combined$GarageType1)
combined <- subset(combined,select = -GarageType1)

# Changing NA in GarageYrBlt to None
combined$GarageYrBlt[which(is.na(combined$GarageYrBlt))] <- 0 

# Changing NA in GarageFinish to None
combined$GarageFinish1 <- as.character(combined$GarageFinish)
combined$GarageFinish1[which(is.na(combined$GarageFinish))] <- "None"
combined$GarageFinish <- as.factor(combined$GarageFinish1)
combined <- subset(combined,select = -GarageFinish1)

# Changing NA in GarageQual to None
combined$GarageQual1 <- as.character(combined$GarageQual)
combined$GarageQual1[which(is.na(combined$GarageQual))] <- "None"
combined$GarageQual <- as.factor(combined$GarageQual1)
combined <- subset(combined,select = -GarageQual1)

# Changing NA in GarageCond to None
combined$GarageCond1 <- as.character(combined$GarageCond)
combined$GarageCond1[which(is.na(combined$GarageCond))] <- "None"
combined$GarageCond <- as.factor(combined$GarageCond1)
combined <- subset(combined,select = -GarageCond1)

# Changing NA in BsmtQual to None
combined$BsmtQual1 <- as.character(combined$BsmtQual)
combined$BsmtQual1[which(is.na(combined$BsmtQual))] <- "None"
combined$BsmtQual <- as.factor(combined$BsmtQual1)
combined <- subset(combined,select = -BsmtQual1)

# Changing NA in BsmtCond to None
combined$BsmtCond1 <- as.character(combined$BsmtCond)
combined$BsmtCond1[which(is.na(combined$BsmtCond))] <- "None"
combined$BsmtCond <- as.factor(combined$BsmtCond1)
combined <- subset(combined,select = -BsmtCond1)

# Changing NA in BsmtExposure to None
combined$BsmtExposure1 <- as.character(combined$BsmtExposure)
combined$BsmtExposure1[which(is.na(combined$BsmtExposure))] <- "None"
combined$BsmtExposure <- as.factor(combined$BsmtExposure1)
combined <- subset(combined,select = -BsmtExposure1)

# Changing NA in BsmtFinType1 to None
combined$BsmtFinType11 <- as.character(combined$BsmtFinType1)
combined$BsmtFinType11[which(is.na(combined$BsmtFinType1))] <- "None"
combined$BsmtFinType1 <- as.factor(combined$BsmtFinType11)
combined <- subset(combined,select = -BsmtFinType11)
# Changing NA in BsmtFinType2 to None
combined$BsmtFinType21 <- as.character(combined$BsmtFinType2)
combined$BsmtFinType21[which(is.na(combined$BsmtFinType2))] <- "None"
combined$BsmtFinType2 <- as.factor(combined$BsmtFinType21)
combined <- subset(combined,select = -BsmtFinType21)

# Changing NA in Electrical to None
combined$Electrical1 <- as.character(combined$Electrical)
combined$Electrical1[which(is.na(combined$Electrical))] <- "None"
combined$Electrical <- as.factor(combined$Electrical1)
combined <- subset(combined,select = -Electrical1)
```


```{r}
levels(combined$MSZoning) <- c(levels(combined$MSZoning),"None")
levels(combined$Utilities) <- c(levels(combined$Utilities),"None","NoSeWa")
levels(combined$Exterior1st) <- c(levels(combined$Exterior1st),"None","ImStucc","Stone")
levels(combined$Exterior2nd) <- c(levels(combined$Exterior2nd),"None","Other")
levels(combined$KitchenQual) <- c(levels(combined$KitchenQual),"None")
levels(combined$Functional) <- c(levels(combined$Functional),"None")
levels(combined$SaleType) <- c(levels(combined$SaleType),"None")
```


```{r}
Column_classes <- sapply(names(combined),function(x){class(combined[[x]])})
numeric_columns <-names(Column_classes[Column_classes != "factor"])
#determining skew of each numric variable
skew <- sapply(numeric_columns,function(x){skewness(combined[[x]],na.rm = T)})
# Let us determine a threshold skewness and transform all variables above the treshold.
skew <- skew[skew > 0.75]

# transform excessively skewed features with log(x + 1)
for(x in names(skew)) {
  combined[[x]] <- log(combined[[x]] + 1)
}
```

```{r}
train <- combined[combined$isTrain==1,]
table(train$MasVnrType)
test <- combined[combined$isTrain==0,]
smp_size <- floor(0.75 * nrow(train))

## setting the seed to make the partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(train)), size = smp_size)

train_new <- train[train_ind, ]
validate <- train[-train_ind, ]
train_new <- subset(train_new,select=-c(Id,isTrain))
validate <- subset(validate,select=-c(Id,isTrain))
nrow(train_new)
nrow(validate)
str(train_new)
```

```{r}
ggplot(train_new,aes(y=GrLivArea,x=as.factor(YrSold)))+geom_boxplot()
```



```{r}
ggplot(train_new,aes(SalePrice))+geom_histogram()
```


```{r}
fit <- lm(SalePrice~.,train)

#taking significant features from here

fit_1 <- lm(SalePrice~MSZoning+I(LotArea^2)+Street+
            LotConfig+LandSlope+Neighborhood+Condition1+OverallQual+OverallCond+
            YearBuilt+RoofStyle+RoofMatl+MasVnrArea+ExterQual+BsmtQual+BsmtExposure+BsmtFinSF2 +
           BsmtUnfSF+X1stFlrSF+X2ndFlrSF+BedroomAbvGr+KitchenQual+GarageQual+
            ScreenPorch+PoolArea+PoolQC,train_new)
summary(fit_1)
plot(fit_1$fit,fit_1$residuals)
abline(h=0,col="blue")
prediction <- predict(fit_1,validate,type = "response")
length(validate$SalePrice)
length(prediction)
```



```{r}
mse <- sqrt(mean((prediction-validate$SalePrice)^2,na.rm=T))
mse
```



```{r}
fit_lm <- lm(SalePrice~MSZoning+LotArea+Street+
            LotConfig+LandSlope+Neighborhood+Condition1+OverallQual+OverallCond+
            YearBuilt+RoofStyle+RoofMatl+MasVnrArea+ExterQual+BsmtQual+BsmtExposure+BsmtFinSF2 +
           BsmtUnfSF+X1stFlrSF+X2ndFlrSF+BedroomAbvGr+KitchenQual+GarageQual+
            ScreenPorch+PoolArea+PoolQC,train)
```




```{r}
Missing_indices <- sapply(test,function(x)sum(is.na(x)))
Missing_Summary <- data.frame(index = names(test),Missing_Values=Missing_indices)
Missing_Summary[Missing_Summary$Missing_Values > 0,]
```


```{r}
# Changing NAs to "None" or 0
test$MSZoning1 <- as.character(test$MSZoning)
test$MSZoning1[which(is.na(test$MSZoning))] <- "None"
test$MSZoning <- as.factor(test$MSZoning1)
test <- subset(test,select = -MSZoning1)

test$Utilities1 <- as.character(test$Utilities)
test$Utilities1[which(is.na(test$Utilities))] <- "None"
test$Utilities <- as.factor(test$Utilities1)
test <- subset(test,select = -Utilities1)

test$Exterior1st1 <- as.character(test$Exterior1st)
test$Exterior1st1[which(is.na(test$Exterior1st))] <- "None"
test$Exterior1st <- as.factor(test$Exterior1st1)
test <- subset(test,select = -Exterior1st1)

test$Exterior2nd1 <- as.character(test$Exterior2nd)
test$Exterior2nd1[which(is.na(test$Exterior2nd))] <- "None"
test$Exterior2nd <- as.factor(test$Exterior2nd1)
test <- subset(test,select = -Exterior2nd1)

test$BsmtFinSF1[which(is.na(test$BsmtFinSF1))] <- 0
test$BsmtFinSF2[which(is.na(test$BsmtFinSF2))] <- 0
test$TotalBsmtSF[which(is.na(test$TotalBsmtSF))] <- 0
test$BsmtUnfSF[which(is.na(test$BsmtUnfSF))] <- 0
test$BsmtFullBath[which(is.na(test$BsmtFullBath))] <- 0
test$BsmtHalfBath[which(is.na(test$BsmtHalfBath))] <- 0



test$KitchenQual1 <- as.character(test$KitchenQual)
test$KitchenQual1[which(is.na(test$KitchenQual))] <- "None"
test$KitchenQual <- as.factor(test$KitchenQual1)
test <- subset(test,select = -KitchenQual1)

test$Functional1 <- as.character(test$Functional)
test$Functional1[which(is.na(test$Functional))] <- "None"
test$Functional <- as.factor(test$Functional1)
test <- subset(test,select = -Functional1)

test$GarageCars[which(is.na(test$GarageCars))] <- 0
test$GarageArea[which(is.na(test$GarageArea))] <- 0

test$SaleType1 <- as.character(test$SaleType)
test$SaleType1[which(is.na(test$SaleType))] <- "None"
test$SaleType <- as.factor(test$SaleType1)
test <- subset(test,select = -SaleType1)
```


```{r}
dummy <- dummyVars(" ~ .",data=train)
train_trans <- data.frame(predict(dummy,newdata=train))
dim(train_trans)

```

```{r}
dummy_test <- dummyVars(" ~ .",data=test)
test_trans <- data.frame(predict(dummy,newdata=test))
dim(test_trans)
```


```{r}
all_predictors <- subset(train,select = -c(Id,isTrain,SalePrice))
var_classes <- sapply(all_predictors,function(x)class(x))
num_classes <- var_classes[var_classes=="integer"]
num_vars <- subset(train,select=names(num_classes))
corrplot(cor(num_vars),method="number")
```


```{r}
myTrainControl <- trainControl(method="repeatedcv",number=10,repeats = 4)
fit.glmnet <- train(SalePrice~.-Id-isTrain,train,trControl = myTrainControl,
                    method="glmnet",tuneGrid=expand.grid(.alpha = seq(0,1,by=0.05), 
                                                         .lambda = seq(0, 0.08, by = 0.01)))
```



```{r}
print(fit.glmnet)
```


```{r}
varImp(fit.glmnet)
```


```{r}
log_prediction <- predict(fit.glmnet,newdata=test)
actual_pred <- exp(log_prediction)-1
hist(actual_pred)
submit <- data.frame(Id=test$Id,SalePrice=actual_pred)
write.csv(submit,file="stroud.csv",row.names=F)
```

