---
title: "Playground"
author: "David Stroud"
date: "2/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2) # Data visualization
library(readr) # CSV file I/O, e.g. the read_csv function
library(dplyr)
```

```{r}
# load the datasets
# note ~ use read.csv to read into Rmd
train <- read.csv("train.csv")
test <- read.csv("test.csv")
summary(train)
str(train)
```            


```{r}
# Show the dimensions of the training data sample
dim(head(train))
```

```{r}
# Show scatter plot ~ 
ggplot(train,aes(y=SalePrice,x=GrLivArea))+geom_point()
```

```{r}
# Remove outliers. Data points where GrLivArea is about 4000
train <- train[train$GrLivArea<=4000,]
```
 
 
```{r}
# The majority of garages were built when the homes were built. Points
# above the line show they were added later
# Consider building a new feature that tells us whether or not a garage
# was originally constructed with the house or when it was added.
ggplot(train,aes(y=GarageYrBlt,x=YearBuilt))+geom_point()
```

```{r}
# Find the number of missing values 
Missing_indices <- sapply(train,function(x)sum(is.na(x)))
Missing_Summary <- data.frame(index=names(train),Missing_Values=Missing_indices)
Missing_Summary[Missing_Summary$Missing_Values > 0,]
```
 
 
```{r}
# Combine the train and test data for a quicker data prep
test$SalePrice <- NA
train$isTrain <- 1
test$isTrain <- 0
combined <- rbind(train,test)
```
 
 
```{r}
combined$MasVnrArea[which(is.na(combined$MasVnrArea))] <- mean(combined$MasVnrArea,na.rm=T)
# Changing NA in Alley to None
combined$Alley1 <- as.character(combined$Alley)
combined$Alley1[which(is.na(combined$Alley))] <- "None"
table(combined$Alley1)
combined$Alley <- as.factor(combined$Alley1)
combined <- subset(combined,select = -Alley1)
```
 
 
 
 